### ISSUE TITLE
crashing on commands in multiplayer

### ISSUE THREAD

**Issue by Ancient77** [RealRTTV/chatcalc#12] opened 2023-12-10 17:25 UTC
The game freezes up every time you are on a server write something like "/r xxx", even without sending it. 
It doesn't happen if you only do "/r xx", and also I couldn't reproduce it on singleplayer. 
Also happens without any other mods installed.

Linux Ubuntu 23.04
Fabric 1.20.1 0.14.25
Chat Calc 3.0.23.b

**Comment by RealRTTV** [comment] 2023-12-11 15:26
can you send the crash report?

**Comment by RealRTTV** [comment] 2023-12-13 15:20
doesn't occur on my end

**Comment by Ancient77** [comment] 2023-12-14 13:30
I don't get any crash logs, the program only freezes until I force close the game. 
It also happens on my windows system: here are the logs :
<details>
<summary> latest.log </summary>

```[14:20:01] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.25
[14:20:01] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[14:20:01] [main/INFO]: Loading 4 mods:
	- chatcalc 3.0.23
	- fabricloader 0.14.25
	- java 17
	- minecraft 1.20.1
[14:20:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:20:01] [main/INFO]: Compatibility level set to JAVA_17
[14:20:09] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 171 milliseconds
[14:20:11] [Render thread/INFO]: [STDERR]: Version: 3.3.1 SNAPSHOT
[14:20:11] [Render thread/INFO]: [STDERR]: 	 OS: Windows 11 v10.0
[14:20:11] [Render thread/INFO]: [STDERR]: 	JRE: Windows amd64 17.0.8
[14:20:11] [Render thread/INFO]: [STDERR]: 	JVM: OpenJDK 64-Bit Server VM v17.0.8+7-LTS by Azul Systems, Inc.
[14:20:11] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl
[14:20:11] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl
[14:20:11] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/lwjgl.dll
[14:20:11] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\lwjgl.dll
[14:20:11] [Render thread/INFO]: [STDERR]: Loading library: jemalloc
[14:20:11] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.jemalloc
[14:20:11] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/jemalloc/jemalloc.dll
[14:20:11] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\jemalloc.dll
[14:20:11] [Render thread/INFO]: [STDERR]: MemoryUtil allocator: JEmallocAllocator
[14:20:11] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:20:12] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[14:20:12] [Render thread/INFO]: [STDERR]: Loading library: glfw
[14:20:12] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.glfw
[14:20:12] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/glfw/glfw.dll
[14:20:12] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\glfw.dll
[14:20:12] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[14:20:12] [Render thread/INFO]: [STDERR]: Java 9 check intrinsics enabled
[14:20:12] [Render thread/INFO]: [STDERR]: Closure Registry: simple
[14:20:13] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl_opengl
[14:20:13] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.opengl
[14:20:13] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/opengl/lwjgl_opengl.dll
[14:20:13] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\lwjgl_opengl.dll
[14:20:13] [Render thread/INFO]: [STDERR]: Loading library: opengl32
[14:20:13] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.opengl
[14:20:13] [Render thread/INFO]: [STDERR]: 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25
[14:20:13] [Render thread/INFO]: [STDERR]: 	Loaded from system paths: C:\WINDOWS\SYSTEM32\opengl32.dll
[14:20:13] [Render thread/INFO]: [STDERR]: Java 10 multiplyHigh enabled
[14:20:13] [Render thread/INFO]: [STDERR]: [GL] GL_OVR_multiview was reported as available but an entry point is missing.
[14:20:13] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl_stb
[14:20:13] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.stb
[14:20:13] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/stb/lwjgl_stb.dll
[14:20:13] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\lwjgl_stb.dll
[14:20:13] [Render thread/INFO]: [STDERR]: Java 9 text decoding enabled
[14:20:13] [Render thread/INFO]: [STDERR]: Loading library: OpenAL
[14:20:13] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.openal
[14:20:13] [Render thread/INFO]: [STDERR]: 	Extracting: file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar!/windows/x64/org/lwjgl/openal/OpenAL.dll
[14:20:13] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.14.25\OpenAL.dll
[14:20:14] [Render thread/INFO]: Reloading ResourceManager: vanilla
[14:20:15] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[14:20:17] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[14:20:17] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[14:20:17] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[14:20:17] [Render thread/INFO]: Sound engine started
[14:20:17] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[14:20:17] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[14:20:17] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[14:20:17] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[14:20:17] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[14:20:17] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[14:20:17] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[14:20:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:20:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[14:20:18] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[14:20:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:20:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:20:18] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:21:43] [Render thread/INFO]: Connecting to hypixel.net, 25565
[14:21:46] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[14:21:47] [Render thread/INFO]: [System] [CHAT]                                      
[14:21:47] [Render thread/INFO]: [System] [CHAT] You are still radiating with �bGenerosity!
[14:21:47] [Render thread/INFO]: [System] [CHAT]                          
[14:21:47] [Render thread/INFO]: [System] [CHAT] �b[MVP�4+�b] {MINECRAFT_USERNAME}�f �6slid into the lobby!
[14:21:47] [Render thread/WARN]: Unknown custom packed identifier: badlion:mods
[14:21:47] [Render thread/INFO]: [System] [CHAT] 
[14:21:47] [Render thread/INFO]: [System] [CHAT] �f�lHAPPY HOLIDAYS �e�lFROM HYPIXEL\n�aYou may claim today's �bAdvent Calendar �areward!\n�eClick here to claim!\n
[14:21:47] [Render thread/INFO]: [System] [CHAT] �e�l????????????????????????????????????????\n�6�lHYPIXEL�e is hosting a �b�lGRINCH SIMULATOR�e tournament!\n�6Compete, climb the leaderboard and earn free rewards!\n�eTo participate, visit the hall �bon December 15th\n�e�lClick �b�lHERE �e�lto read the announcement!\n�e�l????????????????????????????????????????\n
[14:21:47] [Render thread/INFO]: [System] [CHAT] �b[MVP�c+�b] _ByJlo4ka�f �6slid into the lobby!
[14:21:47] [Render thread/INFO]: [STDERR]: Java 10 memcpy enabled
[14:21:49] [Render thread/INFO]: [System] [CHAT] Automatically gifted your 7 gifts to yourself!
[14:21:49] [Render thread/INFO]: [System] [CHAT] Automatically opened your 7 gift bundles!
[14:21:49] [Render thread/INFO]: [System] [CHAT] Automatically opened your 33 Mystery Boxes!
[14:21:49] [Render thread/INFO]: [System] [CHAT] You have received 33 rewards, including 3 new ones: Rare Mage Warrior Hat, Epic Horror Movie Gadget, Rare Elf Suit Boots
[14:21:49] [Render thread/INFO]: [System] [CHAT] 207x Mystery Dust
[14:21:49] [Render thread/INFO]: [System] [CHAT] 1,003x Pet Items
[14:21:51] [Render thread/INFO]: [System] [CHAT] �b[MVP�c+�b] Idhao�f �6slid into the lobby!
[14:21:51] [Render thread/INFO]: [System] [CHAT] �b[MVP�c+�b] Plamsen�f �6slid into the lobby!
```
</details>

**Comment by RealRTTV** [comment] 2023-12-14 13:43
I’ll send you a pre-release later today, is the issue still reproducible?

**Comment by RealRTTV** [comment] 2023-12-14 23:16
https://cdn.discordapp.com/attachments/725512925128949822/1184997409152049232/chatcalc-3.0.24b.jar?ex=658e01d6&is=657b8cd6&hm=e8ec927eed237b0492a386d0d484d960b001c59e49d0d3b455463839e30a7460&

**Comment by Ancient77** [comment] 2023-12-15 11:04
> I’ll send you a pre-release later today, is the issue still reproducible?

Yes, still happening. Tested on windows.

**Comment by Ancient77** [comment] 2023-12-15 11:07
Here is a screenshot from what I see once it crashes.
![image](https://github.com/RealRTTV/chatcalc/assets/76914086/49b696e4-8462-4b7b-b1db-5f3b7a1bff79)

**Comment by Tohru-Kobayashi** [comment] 2023-12-16 09:22
I have the same issue.
The only way to exit once Minecraft softlocks is to use the system 'Program Not Responding' prompt to close it.
It only seems to happen when trying to do math on command arguments (Maybe more, that's all I found in my testing)

- Occurs on multiplayer ONLY (even though singleplayer runs as a local server)

- Minecraft's run time is not a factor (Speculation: I've only let the game idle for 10 minutes so far)

- Occurs with recognized commands, like "/help xx", "/help aa"
          Note: Mod works properly with "/help x", displays value, and
                    when attempting to type the second x, Minecraft softlocks

- Does NOT occur with normal operations [0+1, 1-2, 2/2, 2*2] (tested, not verified with many calculations)

1. Using fabric and mc 1.20.1, windows 10, fapi 15.2
        -Occurs on mod versions 3.021b, 3.022b, 3.023b, 3.024b
        -Does NOT occur on mod versions 3.015, 3.018b, 3.020b
2. Using fabric and mc 1.20.2, windows 10, fapi 15.2
        -Occurs on mod versions 3.021a, 3.022a, 3.023a
        -Does NOT occur on mod versions 3.015, 3.016, 3.017, 3.018, 3.019, 3.020a

**Comment by RealRTTV** [comment] 2023-12-16 20:04
this is so so strange

**Comment by RealRTTV** [comment] 2023-12-16 20:06
.21 was a large update, which was annoying

**Comment by RealRTTV** [comment] 2023-12-16 20:09
> I have the same issue. The only way to exit once Minecraft softlocks is to use the system 'Program Not Responding' prompt to close it. It only seems to happen when trying to do math on command arguments (Maybe more, that's all I found in my testing)
> 
>     * Occurs on multiplayer ONLY (even though singleplayer runs as a local server)
> 
>     * Minecraft's run time is not a factor (Speculation: I've only let the game idle for 10 minutes so far)
> 
>     * Occurs with recognized commands, like "/help xx", "/help aa"
>       Note: Mod works properly with "/help x", displays value, and
>       when attempting to type the second x, Minecraft softlocks
> 
>     * Does NOT occur with normal operations [0+1, 1-2, 2/2, 2*2] (tested, not verified with many calculations)
> 
> 
>     1. Using fabric and mc 1.20.1, windows 10, fapi 15.2
>        -Occurs on mod versions 3.021b, 3.022b, 3.023b, 3.024b
>        -Does NOT occur on mod versions 3.015, 3.018b, 3.020b
> 
>     2. Using fabric and mc 1.20.2, windows 10, fapi 15.2
>        -Occurs on mod versions 3.021a, 3.022a, 3.023a
>        -Does NOT occur on mod versions 3.015, 3.016, 3.017, 3.018, 3.019, 3.020a

I still can't reproduce the issue, is `a` defined as a constant when you try `/help aa` or not?

**Comment by Tohru-Kobayashi** [comment] 2023-12-17 07:59
I am going to attach a video if it will help at all

This is a test on 1.20.2 with chatcalc 3.021a.

Yes, 'x' is defined as a constant, with 'x' being the player coordinate.
I thought 'a' was treated the same way, but it's not. (Will put a new comment below this one to show)

The server in the video is just a random one that was supposedly fully vanilla, but it's running on Purpur/Velocity. (Figured I would test if different server environments affected it)
-The only reason I'm typing "/hd a" here is because this server doesn't let you run /help

I'm using Graalvm java 17 btw, if that has any bearing on the issue.

Is there any debug tool I could use on my end that would show what's going wrong?

https://github.com/RealRTTV/chatcalc/assets/43527214/98f76685-4442-4506-ae87-ea8de15a8637

**Comment by Tohru-Kobayashi** [comment] 2023-12-17 08:21
This is a test on 1.20.2 with chatcalc 3.020a. 

X is definitely defined as a constant here, but it seems A is being treated differently here. 
I might've been wrong before when saying that a and x were both treated exactly the same by chatcalc.


https://github.com/RealRTTV/chatcalc/assets/43527214/44916b67-2c50-417f-b125-382c4d0dd313

**Comment by RealRTTV** [comment] 2023-12-17 18:40
fixed it, turns out the CompletableFuture for suggestions can wait indefinitely, and that's why it wasn't working, new release coming very shortly

**Closed as completed by RealRTTV** 2023-12-17 18:40 UTC

**Comment by RealRTTV** [comment] 2023-12-17 18:45
basically, the server never sent you the suggestions for the commands you were typing, chatcalc has this feature where it sees if you can do tabbing for stuff like `/give @s minecraft:ston` and will try that before trying chatcalc (useful when you try to tab `e` for something and get euler's number), these servers acted non-vanilla like and never sent these suggestions rather than sending empty ones, this made chatcalc wait forever for them to be sent, thus freezing
